### ISSUE TITLE
Running Bug

### ISSUE THREAD

**Issue by backkon** [YCAyca/3D-Multi-Object-Tracking-using-Lidar#1]
There is a bug: when the oxts file I provide is none, the code does not judge whether it is none, but directly reads the oxts, resulting in an error. (in line 292, tracking.py)

**Comment by YCAyca** [comment]
Hello, if you have oxts folder in the same path with your velodyne folder, the code starts using after parsing this oxts path from main path. So if you don't want to use it, you can just quickly change the name of oxts folder to oxts_ or something like that to prevent that the code finds oxts folder and use it directly
